# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Live, Eat, Code."
email: RichG72@Gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is going to be my blog for the next while! I'm pretty excited to start
  it up and I will be explaining my current feats with programming and supply
  you all with some links to go and check out my current projects!

  I'll also be posting code snippets and other things like: technical issues 
  that I run into and just general information about my current life!

  Hope you enjoy!

  -Rich Gautereaux
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: Tripleoughtt
github_username:  Tripleoughtt

# Build settings
markdown: kramdown
